### ISSUE TITLE
RuntimeError: can't modify frozen String

### ISSUE THREAD

**Issue by raghubetina** [ericbeland/html_validation#14]
Hello! When I try using this matcher, I get a `RuntimeError: can't modify frozen String`. Possibly due to different defaults in newer versions of Ruby/Rails?

Here's a brand new Rails 5.1 app that demonstrates the issue:

https://github.com/raghubetina/html_validation_frozen_string

If you `rspec`, you should see what I mean.

Thank you!

**Comment by ericbeland** [comment]
Do you mind pasting in a stack trace if you have one to get me rolling? I'll run the whole app when I have a free block of time.

**Comment by raghubetina** [comment]
Here is the output from `rspec`:

```
Randomized with seed 47339
F

Failures:

  1) Home page: Content is valid HTML
     Failure/Error: expect(page).to have_valid_html

     RuntimeError:
       can't modify frozen String
     # /Users/raghubetina/.rvm/gems/ruby-2.4.1/gems/html_validation-1.1.3/lib/html_validation/page_validations.rb:136:in `gsub!'
     # /Users/raghubetina/.rvm/gems/ruby-2.4.1/gems/html_validation-1.1.3/lib/html_validation/page_validations.rb:136:in `filenameize'
     # /Users/raghubetina/.rvm/gems/ruby-2.4.1/gems/html_validation-1.1.3/lib/html_validation/page_validations.rb:115:in `validation'
     # /Users/raghubetina/.rvm/gems/ruby-2.4.1/gems/html_validation-1.1.3/lib/html_validation/have_valid_html.rb:19:in `matches?'
     # ./spec/features/home_page_spec.rb:6:in `block (3 levels) in <top (required)>'

Finished in 0.004 seconds (files took 2.64 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/home_page_spec.rb:5 # Home page: Content is valid HTML

Randomized with seed 47339
```

Thanks so much!

**Comment by ericbeland** [comment]
I pushed up a new build.

**Comment by raghubetina** [comment]
That did it! Thank you so much.
